spring.application.name=PhoBo

# PostgreSQL Connection (?ã s?a l?i comment cho ?úng lo?i DB)
spring.datasource.url=jdbc:postgresql://localhost:5432/minboo-local
spring.datasource.username=postgres
spring.datasource.password=courage1530
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect