name: Java CI with Maven

# When should the robot wake up ?
on:
    push:
    pull_request:
        branches: [ "main" ]
        
jobs:
    build:
        runs-on: ubuntu-latest # OS which machine will run
        
        steps:
        - name: 1. Download code
          uses: actions/checkout@v6
          
        - name: 2. Install Java
          uses: actions/setup-java@v5
          with:
            java-version: '25'
            distribution: 'temurin'
            cache: 'maven'
            
        - name: 3. Compile Syntax Check
          run: mvn clean compile
        